api_storage_file_index:
    methods: [GET]
    path: storage-file
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::index

api_storage_file_create:
    methods: [POST]
    path: storage-file
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::create

api_storage_file_view:
    methods: [GET]
    path: storage-file/{id}
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::view
    requirements:
        id: '\d+'

api_storage_file_update:
    methods: [PUT]
    path: storage-file/{id}
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::update
    requirements:
        id: '\d+'

api_storage_file_delete:
    methods: [DELETE]
    path: storage-file/{id}
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::delete
    requirements:
        id: '\d+'

api_storage_file_index_options:
    methods: [OPTIONS]
    path: storage-file
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::options

api_storage_file_options:
    methods: [OPTIONS]
    path: storage-file/{id}
    controller: ZnBundle\Storage\Symfony\Api\Controllers\FileController::options
    requirements:
        id: '\d+'
